//! Port of zuyu/src/common/logging/types.h
//! Status: COMPLET
//! Derniere synchro: 2026-03-05

/// Specifies the severity or level of detail of the log message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u8)]
pub enum Level {
    /// Extremely detailed and repetitive debugging information that is likely to pollute logs.
    Trace = 0,
    /// Less detailed debugging information.
    Debug = 1,
    /// Status information from important points during execution.
    Info = 2,
    /// Minor or potential problems found during execution of a task.
    Warning = 3,
    /// Major problems found during execution of a task that prevent it from being completed.
    Error = 4,
    /// Major problems during execution that threaten the stability of the entire application.
    Critical = 5,
}

impl Level {
    pub const COUNT: usize = 6;

    pub fn from_u8(v: u8) -> Option<Self> {
        match v {
            0 => Some(Level::Trace),
            1 => Some(Level::Debug),
            2 => Some(Level::Info),
            3 => Some(Level::Warning),
            4 => Some(Level::Error),
            5 => Some(Level::Critical),
            _ => None,
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Level::Trace => "Trace",
            Level::Debug => "Debug",
            Level::Info => "Info",
            Level::Warning => "Warning",
            Level::Error => "Error",
            Level::Critical => "Critical",
        }
    }
}

/// Specifies the sub-system that generated the log message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
#[allow(non_camel_case_types)]
pub enum Class {
    Log = 0,
    Common,
    Common_Filesystem,
    Common_Memory,
    Core,
    Core_ARM,
    Core_Timing,
    Config,
    Debug,
    Debug_Emulated,
    Debug_GPU,
    Debug_Breakpoint,
    Debug_GDBStub,
    Kernel,
    Kernel_SVC,
    Service,
    Service_ACC,
    Service_AM,
    Service_AOC,
    Service_APM,
    Service_ARP,
    Service_Audio,
    Service_BCAT,
    Service_BGTC,
    Service_BPC,
    Service_BTDRV,
    Service_BTM,
    Service_Capture,
    Service_ERPT,
    Service_ETicket,
    Service_EUPLD,
    Service_Fatal,
    Service_FGM,
    Service_Friend,
    Service_FS,
    Service_GRC,
    Service_HID,
    Service_IRS,
    Service_JIT,
    Service_LBL,
    Service_LDN,
    Service_LDR,
    Service_LM,
    Service_Migration,
    Service_Mii,
    Service_MM,
    Service_MNPP,
    Service_NCM,
    Service_NFC,
    Service_NFP,
    Service_NGC,
    Service_NIFM,
    Service_NIM,
    Service_NOTIF,
    Service_NPNS,
    Service_NS,
    Service_NVDRV,
    Service_Nvnflinger,
    Service_OLSC,
    Service_PCIE,
    Service_PCTL,
    Service_PCV,
    Service_PM,
    Service_PREPO,
    Service_PSC,
    Service_PTM,
    Service_SET,
    Service_SM,
    Service_SPL,
    Service_SSL,
    Service_TCAP,
    Service_Time,
    Service_USB,
    Service_VI,
    Service_WLAN,
    HW,
    HW_Memory,
    HW_LCD,
    HW_GPU,
    HW_AES,
    IPC,
    Frontend,
    Render,
    Render_Software,
    Render_OpenGL,
    Render_Vulkan,
    Shader,
    Shader_SPIRV,
    Shader_GLASM,
    Shader_GLSL,
    Audio,
    Audio_DSP,
    Audio_Sink,
    Loader,
    CheatEngine,
    Crypto,
    Input,
    Network,
    WebService,
}

impl Class {
    pub const COUNT: usize = 97;

    pub fn name(self) -> &'static str {
        match self {
            Class::Log => "Log",
            Class::Common => "Common",
            Class::Common_Filesystem => "Common.Filesystem",
            Class::Common_Memory => "Common.Memory",
            Class::Core => "Core",
            Class::Core_ARM => "Core.ARM",
            Class::Core_Timing => "Core.Timing",
            Class::Config => "Config",
            Class::Debug => "Debug",
            Class::Debug_Emulated => "Debug.Emulated",
            Class::Debug_GPU => "Debug.GPU",
            Class::Debug_Breakpoint => "Debug.Breakpoint",
            Class::Debug_GDBStub => "Debug.GDBStub",
            Class::Kernel => "Kernel",
            Class::Kernel_SVC => "Kernel.SVC",
            Class::Service => "Service",
            Class::Service_ACC => "Service.ACC",
            Class::Service_AM => "Service.AM",
            Class::Service_AOC => "Service.AOC",
            Class::Service_APM => "Service.APM",
            Class::Service_ARP => "Service.ARP",
            Class::Service_Audio => "Service.Audio",
            Class::Service_BCAT => "Service.BCAT",
            Class::Service_BGTC => "Service.BGTC",
            Class::Service_BPC => "Service.BPC",
            Class::Service_BTDRV => "Service.BTDRV",
            Class::Service_BTM => "Service.BTM",
            Class::Service_Capture => "Service.Capture",
            Class::Service_ERPT => "Service.ERPT",
            Class::Service_ETicket => "Service.ETicket",
            Class::Service_EUPLD => "Service.EUPLD",
            Class::Service_Fatal => "Service.Fatal",
            Class::Service_FGM => "Service.FGM",
            Class::Service_Friend => "Service.Friend",
            Class::Service_FS => "Service.FS",
            Class::Service_GRC => "Service.GRC",
            Class::Service_HID => "Service.HID",
            Class::Service_IRS => "Service.IRS",
            Class::Service_JIT => "Service.JIT",
            Class::Service_LBL => "Service.LBL",
            Class::Service_LDN => "Service.LDN",
            Class::Service_LDR => "Service.LDR",
            Class::Service_LM => "Service.LM",
            Class::Service_Migration => "Service.Migration",
            Class::Service_Mii => "Service.Mii",
            Class::Service_MM => "Service.MM",
            Class::Service_MNPP => "Service.MNPP",
            Class::Service_NCM => "Service.NCM",
            Class::Service_NFC => "Service.NFC",
            Class::Service_NFP => "Service.NFP",
            Class::Service_NGC => "Service.NGC",
            Class::Service_NIFM => "Service.NIFM",
            Class::Service_NIM => "Service.NIM",
            Class::Service_NOTIF => "Service.NOTIF",
            Class::Service_NPNS => "Service.NPNS",
            Class::Service_NS => "Service.NS",
            Class::Service_NVDRV => "Service.NVDRV",
            Class::Service_Nvnflinger => "Service.Nvnflinger",
            Class::Service_OLSC => "Service.OLSC",
            Class::Service_PCIE => "Service.PCIE",
            Class::Service_PCTL => "Service.PCTL",
            Class::Service_PCV => "Service.PCV",
            Class::Service_PM => "Service.PM",
            Class::Service_PREPO => "Service.PREPO",
            Class::Service_PSC => "Service.PSC",
            Class::Service_PTM => "Service.PTM",
            Class::Service_SET => "Service.SET",
            Class::Service_SM => "Service.SM",
            Class::Service_SPL => "Service.SPL",
            Class::Service_SSL => "Service.SSL",
            Class::Service_TCAP => "Service.TCAP",
            Class::Service_Time => "Service.Time",
            Class::Service_USB => "Service.USB",
            Class::Service_VI => "Service.VI",
            Class::Service_WLAN => "Service.WLAN",
            Class::HW => "HW",
            Class::HW_Memory => "HW.Memory",
            Class::HW_LCD => "HW.LCD",
            Class::HW_GPU => "HW.GPU",
            Class::HW_AES => "HW.AES",
            Class::IPC => "IPC",
            Class::Frontend => "Frontend",
            Class::Render => "Render",
            Class::Render_Software => "Render.Software",
            Class::Render_OpenGL => "Render.OpenGL",
            Class::Render_Vulkan => "Render.Vulkan",
            Class::Shader => "Shader",
            Class::Shader_SPIRV => "Shader.SPIRV",
            Class::Shader_GLASM => "Shader.GLASM",
            Class::Shader_GLSL => "Shader.GLSL",
            Class::Audio => "Audio",
            Class::Audio_DSP => "Audio.DSP",
            Class::Audio_Sink => "Audio.Sink",
            Class::Loader => "Loader",
            Class::CheatEngine => "CheatEngine",
            Class::Crypto => "Crypto",
            Class::Input => "Input",
            Class::Network => "Network",
            Class::WebService => "WebService",
        }
    }

    /// Returns an iterator over all Class variants.
    pub fn all() -> impl Iterator<Item = Class> {
        ALL_CLASSES.iter().copied()
    }

    /// Parse a class name (e.g. "Service.FS") into a Class variant.
    pub fn from_name(name: &str) -> Option<Class> {
        ALL_CLASSES.iter().copied().find(|c| c.name() == name)
    }
}

/// All log classes in order, for iteration.
const ALL_CLASSES: &[Class] = &[
    Class::Log,
    Class::Common,
    Class::Common_Filesystem,
    Class::Common_Memory,
    Class::Core,
    Class::Core_ARM,
    Class::Core_Timing,
    Class::Config,
    Class::Debug,
    Class::Debug_Emulated,
    Class::Debug_GPU,
    Class::Debug_Breakpoint,
    Class::Debug_GDBStub,
    Class::Kernel,
    Class::Kernel_SVC,
    Class::Service,
    Class::Service_ACC,
    Class::Service_AM,
    Class::Service_AOC,
    Class::Service_APM,
    Class::Service_ARP,
    Class::Service_Audio,
    Class::Service_BCAT,
    Class::Service_BGTC,
    Class::Service_BPC,
    Class::Service_BTDRV,
    Class::Service_BTM,
    Class::Service_Capture,
    Class::Service_ERPT,
    Class::Service_ETicket,
    Class::Service_EUPLD,
    Class::Service_Fatal,
    Class::Service_FGM,
    Class::Service_Friend,
    Class::Service_FS,
    Class::Service_GRC,
    Class::Service_HID,
    Class::Service_IRS,
    Class::Service_JIT,
    Class::Service_LBL,
    Class::Service_LDN,
    Class::Service_LDR,
    Class::Service_LM,
    Class::Service_Migration,
    Class::Service_Mii,
    Class::Service_MM,
    Class::Service_MNPP,
    Class::Service_NCM,
    Class::Service_NFC,
    Class::Service_NFP,
    Class::Service_NGC,
    Class::Service_NIFM,
    Class::Service_NIM,
    Class::Service_NOTIF,
    Class::Service_NPNS,
    Class::Service_NS,
    Class::Service_NVDRV,
    Class::Service_Nvnflinger,
    Class::Service_OLSC,
    Class::Service_PCIE,
    Class::Service_PCTL,
    Class::Service_PCV,
    Class::Service_PM,
    Class::Service_PREPO,
    Class::Service_PSC,
    Class::Service_PTM,
    Class::Service_SET,
    Class::Service_SM,
    Class::Service_SPL,
    Class::Service_SSL,
    Class::Service_TCAP,
    Class::Service_Time,
    Class::Service_USB,
    Class::Service_VI,
    Class::Service_WLAN,
    Class::HW,
    Class::HW_Memory,
    Class::HW_LCD,
    Class::HW_GPU,
    Class::HW_AES,
    Class::IPC,
    Class::Frontend,
    Class::Render,
    Class::Render_Software,
    Class::Render_OpenGL,
    Class::Render_Vulkan,
    Class::Shader,
    Class::Shader_SPIRV,
    Class::Shader_GLASM,
    Class::Shader_GLSL,
    Class::Audio,
    Class::Audio_DSP,
    Class::Audio_Sink,
    Class::Loader,
    Class::CheatEngine,
    Class::Crypto,
    Class::Input,
    Class::Network,
    Class::WebService,
];
