pub mod fp_convert;
pub mod fp_mul_add;
pub mod fp_recip_estimate;
pub mod fp_recip_exponent;
pub mod fp_recip_step_fused;
pub mod fp_round_int;
pub mod fp_rsqrt_estimate;
pub mod fp_rsqrt_step_fused;
pub mod fp_to_fixed;

#[cfg(test)]
mod tests {
    use super::fp_recip_estimate::fp_recip_estimate;
    use super::fp_rsqrt_estimate::fp_rsqrt_estimate;
    use crate::common::fp::fpcr::Fpcr;
    use crate::common::fp::fpsr::Fpsr;
    use crate::common::fp::info::FloatFormat;

    fn next_random(state: &mut u64) -> u64 {
        *state ^= *state << 13;
        *state ^= *state >> 7;
        *state ^= *state << 17;
        *state
    }

    fn mix(hash: &mut u64, value: u64) {
        *hash ^= value;
        *hash = hash.wrapping_mul(0x100000001b3);
    }

    fn hash_estimates<F: FloatFormat>(state: &mut u64, hash: &mut u64) {
        const FPCR_VALUES: [u32; 8] = [
            0,
            1 << 24,
            1 << 25,
            (1 << 24) | (1 << 25),
            1 << 19,
            1 << 22,
            2 << 22,
            3 << 22,
        ];

        for fpcr_value in FPCR_VALUES {
            for _ in 0..10_000 {
                let input = F::from_bits(next_random(state));

                let mut recip_fpsr = Fpsr::default();
                let recip = fp_recip_estimate(input, Fpcr::new(fpcr_value), &mut recip_fpsr);
                mix(hash, input.to_bits());
                mix(hash, recip.to_bits());
                mix(hash, recip_fpsr.value() as u64);

                let mut rsqrt_fpsr = Fpsr::default();
                let rsqrt = fp_rsqrt_estimate(input, Fpcr::new(fpcr_value), &mut rsqrt_fpsr);
                mix(hash, rsqrt.to_bits());
                mix(hash, rsqrt_fpsr.value() as u64);
            }
        }
    }

    #[test]
    fn randomized_estimates_match_upstream_digest() {
        let mut state = 0x4d59_5df4_d0f3_3173;
        let mut hash = 0xcbf2_9ce4_8422_2325;

        hash_estimates::<u16>(&mut state, &mut hash);
        hash_estimates::<u32>(&mut state, &mut hash);
        hash_estimates::<u64>(&mut state, &mut hash);

        // Generated by the same sequence against upstream FPRecipEstimate
        // and FPRSqrtEstimate from the pinned zuyu Dynarmic source tree.
        assert_eq!(hash, 0x4cb2_92e1_d75f_95e7);
    }
}
