// SPDX-FileCopyrightText: Copyright 2024 yuzu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

//! Port of zuyu/src/core/hle/service/vi/system_display_service.cpp/.h

pub const ISYSTEM_DISPLAY_SERVICE_COMMANDS: &[(u32, bool, &str)] = &[
    (1200, true, "GetZOrderCountMin"),
    (1202, true, "GetZOrderCountMax"),
    (1203, true, "GetDisplayLogicalResolution"),
    (1204, true, "SetDisplayMagnification"),
    (2201, true, "SetLayerPosition"),
    (2203, true, "SetLayerSize"),
    (2204, true, "GetLayerZ"),
    (2205, true, "SetLayerZ"),
    (2207, true, "SetLayerVisibility"),
    (2209, true, "SetLayerAlpha"),
    (2210, true, "SetLayerPositionAndSize"),
    (2312, true, "CreateStrayLayer"),
    (3000, true, "ListDisplayModes"),
    (3001, true, "ListDisplayRgbRanges"),
    (3002, true, "ListDisplayContentTypes"),
    (3200, true, "GetDisplayMode"),
    (3201, true, "SetDisplayMode"),
    (3202, true, "GetDisplayUnderscan"),
    (3203, true, "SetDisplayUnderscan"),
    (3205, true, "GetDisplayContentType"),
    (3206, true, "SetDisplayContentType"),
    (3207, true, "GetDisplayRgbRange"),
    (3208, true, "SetDisplayRgbRange"),
    (3209, true, "GetDisplayCmuMode"),
    (3210, true, "SetDisplayCmuMode"),
    (3211, true, "GetDisplayContrastRatio"),
    (3212, true, "SetDisplayContrastRatio"),
    (3213, true, "GetDisplayGamma"),
    (3214, true, "SetDisplayGamma"),
    (3215, true, "GetDisplayCmuLuma"),
    (3216, true, "SetDisplayCmuLuma"),
    (3217, true, "SetDisplayCmuSaturation"),
    (8225, true, "GetSharedBufferMemoryHandleId"),
    (8250, true, "OpenSharedLayer"),
    (8251, true, "CloseSharedLayer"),
    (8252, true, "ConnectSharedLayer"),
    (8253, true, "DisconnectSharedLayer"),
    (8254, true, "AcquireSharedFrameBuffer"),
    (8255, true, "PresentSharedFrameBuffer"),
    (8256, true, "GetSharedFrameBufferAcquirableEvent"),
    (8257, true, "FillSharedFrameBufferColor"),
    (8258, true, "CancelSharedFrameBuffer"),
];
